### ISSUE TITLE
Supporting Animations

### ISSUE THREAD

**Issue by willsam100** [fsprojects/Fabulous#183]
The roadmap in this repo states that supporting animations is coming. 
Being able to use the XamarinForms animations would be a huge win for this project. 

Is there an estimation/guess on when this work will be started/completed. 

Alternatively, is there planned architecture for this, allowing the community to contribute?

**Comment by dsyme** [comment]
It's a great question. The relevant C# version of the functionality is here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple.  Basically each view element can now become a task in a little animation DSL. There are also added features of easing functions and custom animations.

This raises a number of issues: views are non-temporal and thus animations are a problem.  I'd like to know what Elmish frameworks do for this, short of programming up the animation manually.

I assume views would need to include a limited amount of temporal information, but obviously you can't restart animations on every view invocation. There is also the question of cancelling animations, and running them in parallel (including parallel animations of unrelated items).

For example, perhaps ViewElements could describe their future animation but subject to a model-held token which indicates the `start` of the animation, e.g.

```
let update msg model = 
    match msg with 
    ... -> { model with Animate= StartAnimation() }

let view ... = 
    ....
    View.Image(...).WithAnimation(model.Animate, ScaleTo (1, 2000))
    ...
```
Cancellation would then be `model.Animate.Cancel()` at some point.

This however doesn't cover animation of two otherwise unrelated view elements, e.g. 
```
await Task.WhenAny<bool>
(
  image.RotateTo (360, 4000),
  image.ScaleTo (2, 2000)
);
```
Maybe you could hack in something like this:
```
let image1 = None
let image2 = None

let update msg model = 
    match msg with 
    | ... -> { model with Animate= StartAnimation() }

let view ... = 
    View.StackLayout [
       View.Image(..., created= (fun v -> image1 <- Some v));
       View.Image(..., created= (fun v -> image2 <- Some v))
    ]..WithAnimation(model.Animate, 
              Animation.WaitAll [
                     Animation.ScaleTo (image1,1, 2000); 
                     Animation.ScaleTo (image2,1, 2000)
              ])
    ...
```
but it's not exactly ideal.  And async/task programming is actually a lovely way of specifying animations and it would be kind of good to use it.

**Comment by dsyme** [comment]
Hi @willsam100 

Animations appear to be possible with #190 

Example for animation triggered on creation of underlying control (note: untested as yet due to technical issue on my laptop).  This isn't a particularly great way of doing things because the underlying control might be recycled if your view is highly dynamic, but is likely useful in many situations anyway because it is simple:

    View.Label(text="Rotate", created=(fun l -> l.RotateTo (360.0, 2000u) |> ignore)) 

Example for animation triggered on message (note: untested as yet due to technical issue on my laptop):

    let animatedLabelRef = ViewRef<Label>()

    let update msg model =
        match msg with 
        | Poked -> 
            match animatedLabelRef.TryValue with 
            | None -> () 
            | Some c -> c.RotateTo (360.0, 2000u) |> ignore

    let view dispatch model = 
        ...
           View.Label(text="Rotate", ref=animatedLabelRef) 
           View.Button(text="Rotate", command=(fun () -> dispatch Poked)) 
        ....

The `ViewRef` pattern is similar to refs in React.   Beware using `Value` on a `ViewRef` too early since you will get an exception if the underlying control for the element has not yet been created.  Also the `ViewRef` only holds a weak handle so the control may also be garbage collected.  This is why `TryValue` is used above.

**Comment by dsyme** [comment]
@willsam100 OK, this is in, though the nuget has not yet been released (@TimLariviere when you're ready would you like to crank the handle on that?  I'll be busy with open fsharp for the next couple of days).

Scant docs are up here: https://fsprojects.github.io/Fabulous/views-animations.html#viewrefs.  We should show corresponding F# samples for all of https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/.

The model is imperfect and may need to be tweaked/improved/adjusted.  @willsam100 if you'd like to give it a go that would be great.
