### ISSUE TITLE
ListView does not reuse it's 'items' ViewElements

### ISSUE THREAD

**Issue by kevinha** [fsprojects/Fabulous#198]
In the attached repro the items of the ListView are labels and the text of the first label changes in response to a scheduled message. According to debug logs the labels are recreated every time the view function is called and none are reused. This appears to be due to the canReuse function at ViewConverters.fs#L271

`updateCollectionGeneric (ValueOption.map seqToArray prevCollOpt) (ValueOption.map seqToArray collOpt) targetColl ListElementData (fun _ _ _ -> ()) (fun _ _ -> false) (fun _ _ _ -> failwith "no element reuse")`

always returning false.

In the repro there is a reference to my local debug build of Fabulous.Core which will need to be replaced.

**Comment by kevinha** [comment]
Fix repro, maybe

[ListViewItemsCreateRepro.zip](https://github.com/fsprojects/Fabulous/files/2430777/ListViewItemsCreateRepro.zip)

**Comment by TimLariviere** [comment]
You're right, L271 voluntarily prevents reusing cells because of how ListView works (ItemsSource, DataTemplate)
Items don't have access to the ViewCell, thus can't update it using the view diffing of Fabulous. (they will only end up updating the root `ListElementData<ViewElement>` which is not a control.
https://github.com/fsprojects/Fabulous/blob/f1ae29aa84abe188cb2fe347c7edda11079c2f17/src/Fabulous.Core/ViewConverters.fs#L263-L271

I think L216 is where the problem lies in reality.

https://github.com/fsprojects/Fabulous/blob/f1ae29aa84abe188cb2fe347c7edda11079c2f17/src/Fabulous.Core/ViewConverters.fs#L211-L217
Replacing the previous `ListElementData` with a new one here will trigger 2 events on the ObservableCollection: Removed, Added
This tells the ListView, for every row, to remove it and add a new one, which is confirmed by `ViewElementCell.OnBindingContextChanged` being called on 2 occasions (first time creation: prev == null & curr = value, and destruction: prev != null && curr = null).

I think the fix should be to implement `INotifyPropertyChanged` on `ListElementData` (and `ListGroupData`).
And instead of replacing the `ListElementData` on update, we replace its content (the `ViewElement`) and trigger a `PropertyChanged` to force `ViewElementCell.OnBindingContextChanged` to reevaluate.
