### ISSUE TITLE
Removing the 'dispatch' function from the view function

### ISSUE THREAD

**Issue by pauldorehill** [fsprojects/Fabulous#322]
Having now spent some time playing with Fabulous (and really enjoying using it!) I became curious as to why the update function requires the `dispatch` function to be passed in which is a little different to Elm. Apologies if there is a well know design reason for it and please let me know if there is!

**Fabulous**
```FSharp
model : 'model
update : 'msg -> 'model -> 'model
view : 'model -> ('msg -> unit) ->  ViewElement
```

**Elm**
```Elm
model : Model
update : Msg -> Model -> Model
view : Model ->  Html Msg
```

When starting with Fabulous it seemed a little odd to have this parameter and it seems Jamie was [confused](https://github.com/fsprojects/Fabulous/issues/263). From looking through the code I think its there to ensure type safety for the commands on the ViewElements? This lead me to think could `ViewElement` be defined as `ViewElement<'msg>` in something like the following pseudo code:

```FSharp
type ViewElement<'msg> = 
    { text : string
      command : 'msg option 
      children : ViewElement<'msg> list option }
    member x.Create() : obj = new obj()
    member x.UpdateIncremental(prev: ViewElement<'msg>, target: obj) : unit = ()

type View() =
    static member inline Button<'msg> (text: string, command : 'msg) = { text = text; command = Some command; children = None }
    static member inline Label (text: string) = { text = text; command = None; children = None }
    static member inline ContentPage (children : ViewElement<'msg> list) = { text = ""; command = None; children = Some children }

    type Model = { Count : int }
    type Msg = Increment
    let init () = { Count = 0 }

    let update (msg : Msg) (model : Model) : Model =
        match msg with 
        | Increment -> { model with Count = model.Count + 1 }

    let view (model : Model) =
        View.ContentPage(
            children =
                [ View.Label(text = string model.Count)
                  View.Button(text = "Increment", command = Increment)])

    let program = mkSimple init update view
```

This constrains the command to all be of type `Msg` and would give the classic elm architecture of:

```FSharp
model : 'model
update : 'msg -> 'model -> 'model
view : 'model ->  ViewElement<'msg>
```
Not sure if this is possible or desirable but I thought I would ask the question?

**Comment by kirillpadx** [comment]
I might be completely wrong here, but these are the cons / pros that I see in using `Elm` style:

cons:
* Less freedom in using various `dispatch` functions for different parts of your app - architecture constraint. Example - as a **Parent** module give your **Child** a dispatch function in such a format `ParentMsg.ChildMsg >> dispatch`, so it would be able to dispatch messages without any additional `map`s.
pros:
* Less verbose code

**Comment by pauldorehill** [comment]
@kirillpadx thanks for starting the conversation. In answer to your cons, part of the reason I suggested this is that having the dispatch function defined in its current form allows for the use of any `dispatch` function in the app which is not so intuitive and I think allows in possible errors. A very contrived example that compiles but doesn't work would be: 
```FSharp
let view (model: Model) dispatch =
    let localDispatch msg =  ()
    View.ContentPage(
        View.StackLayout(
            children =
                [ View.Button(text = sprintf "Click Me: %i" model.Count , command = fun () -> dispatch Ping)
                  View.Button(text = sprintf "Click Me Upper Ping: %i" model.Count , command = fun () -> localDispatch Ping) ]
        )
    )
```

**Comment by bra1nDump** [comment]
Additional cons/pros for suggested change by @pauldorehill 

Cons:
* In our project at work we have *used outside Xamarin libraries*, more specifically [Mapbox](https://github.com/NAXAM/mapbox-xamarin-forms) and we were passing [Actions](https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=netframework-4.7.2) in the view function to our ViewElement wrappers. I suspect for such a case *implementing a wrapper would become a little more tedious*. 
Instead of setting the `Mapbox.Map.ZoomLevelChanged` attribute to `Action(fun arg -> dispatch (XamarinLibraryEventArg arg))` we would have to come up with a way to get a reference to the dispatch function, so we could dispatch the message passed in as argument to `Fabulous.DynamicView.MyView` on the wrapper level. Which kind of brings me to the next point
* How exactly are we going to reference the dispatch function at the time of constructing the view? Not only that, we would need to figure out how to make it happen so the type system is happy (`dispatch: 'msg -> ()`), right? Just in general I have no idea how to make this happen (also remember that nesting views like even in your example will add more typing constraints)
* Need for additional lifting functions [Elm Html.map](https://package.elm-lang.org/packages/elm/html/latest/Html#map)
* What if I don't want to dispatch any Msg at all, say I am debugging and I just want to see if the function is being called when I press the button? (this one sounds especially dumb)

Pros:
* **Stricter typing**: definitely the example you have provided shows the downside of the current approach

Even though I have listed multiple reasons why the current approach makes sense, the typing argument is still very heavy and I actually think I have made mistakes similar to what you have described. Just rambling, hope this is useful.

(kirillpadx was me, I just decieded to merge the two accounts)

**Comment by pauldorehill** [comment]
Apologies for the long delay in my reply... I've been busy at work. In trying to answer your points:

- For custom renderers and a like there would be a need to use and pass in a global `dispatch` function which was previously there https://github.com/fsprojects/Fabulous/blob/244f61aa1ea7f5be00b2a165f6077a0f068e031a/src/Fabulous.Core/ViewHelpers.fs#L42

- There would be no need to reference the dispatch function at all, rather all the views are constructed with the `Msg` only - the same as Elm.

- I currently use a lot of different `msg` types to break my app down into smaller pieces, then wrap them all into a final msg type. Its then just a case of using function composition and not really a need for lifting functions.

```Fsharp
type SubMsg1 =  | SubMsg1
type SubMsg2 = | SubMsg2

type Msg =
     | Msg1 of SubMsg1
     | Msg2 of SubMsg2

View.(... command = (fun () -> SubMsg1 |> Msg1 |> dispatch) ...) etc.
```
 #437 its mentioned that the M-U is roughly the same as Elmish which also has the dispatch function. Maybe @TimLariviere  can shed some light on why we expose the dispatch function?

**Comment by TimLariviere** [comment]
Disclaimer: I'm not familiar with Elm. But I'm currently looking at what other declarative UI frameworks do. Will look at Elm as well.

>Maybe @TimLariviere can shed some light on why we expose the dispatch function?

Like I said in my comment in #437, some part of Fabulous comes directly from Elmish. So we inherited this dispatch function.

I think it was implemented a little differently from Elm to allow more freedom in how we dispatch messages.
Also I think it became necessary to support `Subscription` (workers that can randomly send messages at any point in time)
https://fsprojects.github.io/Fabulous/update.html#triggering-commands-from-external-events

That said, removing `dispatch` from the `view` function has some attractions to it.
It would allow us to be more declarative, instead of a mix of declarative and imperative.

Really need to weigh the pros and cons.

**Comment by et1975** [comment]
Just adding 2c: if I had control over view DSL (as Fabulous does), I'd have avoided passing `dispatch` explicitly. This has nothing to do with Elmish (which still needs to pass the dispatch into whatever renderes the view) and everything to do with the DSL that was available to implement Elmish.React. If you look at the [issue](https://github.com/elmish/react/issues/39) it is still on my mind.

**Comment by TimLariviere** [comment]
Thanks for sharing!
Removing this dispatch function would remove a whole class of errors.

This would also solve our dilemma with `dependsOn` which currently captures `dispatch`.
It requires us to do weird things to keep this cache valid when reloading the app through LiveUpdate

**Comment by dsyme** [comment]
> Removing this dispatch function would remove a whole class of errors.

Yes, it would!  And it just becomes much easier to recycle objects via precise object identity.

**Comment by TimLariviere** [comment]
@dsyme Should we find another way to use the `created` attribute?
If we remove `dispatch`, it would be the only function left that we store in the ViewElement.

**Comment by dsyme** [comment]
> @dsyme Should we find another way to use the created attribute? If we remove dispatch, it would be the only function left that we store in the ViewElement.

Interesting.   It doesn't seem urgent since it is so rarely used, and workarounds would exist to statically allocate that function, but yes it would be great if it were possible.

**Comment by TimLariviere** [comment]
v2 removes dispatch from the view function :)
