### ISSUE TITLE
Apps crash on simple view errors even when using LiveUpdate

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#339]
I did some app building last night with Fabulous and noticed a few things that interrupted the LiveUpdate experience:

* Using a bad font size (`fontSize = "Huge"`) brings down app with a crash at least when using LiveUpdate

* Invalid negative grid row did the same

**Comment by TimLariviere** [comment]
We will now catch all the exceptions in the case LiveUpdate tries to change the running program but it fails to run due to an invalid view.

Those exceptions will still happen at the initial run of the application because if the initial view is invalid, we won't be able to be in a valid state to continue.
