### ISSUE TITLE
Where's footerTemplate, itemTemplate and groupHeaderTemplate of ListView?

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#362]
![image](https://user-images.githubusercontent.com/19922066/54602233-1332b080-4a7c-11e9-8ac7-c4b18afe955a.png)

**Comment by TimLariviere** [comment]
@Happypig375 `*Template` properties are only useful when using data binding.
In Fabulous, data binding is no longer needed due to the way we build the view (the view is reconstructed instead of raising property changed events).

`HeaderTemplate` is a mistake I think, and we should remove it.

You should use `Footer` instead of `FooterTemplate`, and `Items` instead of `ItemsSource/ItemTemplate`.
https://fsprojects.github.io/Fabulous/views-elements.html#lists-and-tables

For grouping, you can use `ListViewGrouped` which needs a list of tuples for the `items` property.
https://github.com/fsprojects/Fabulous/blob/246062ff10cdd53f710056881d70838953045f92/samples/AllControls/AllControls/AllControls.fs#L639-L655

**Comment by Happypig375** [comment]
Thanks

**Comment by gobeiil** [comment]
Hi, 

On a similar note, I'm trying to assign a view element to the header of my ListView. When doing so, Fabulous calls ToString() on my element (or so I believe)

![image](https://user-images.githubusercontent.com/11963284/57971121-cb36e980-7957-11e9-9c96-b9046922cf1a.png)

![image](https://user-images.githubusercontent.com/11963284/57971107-ac385780-7957-11e9-82aa-05c75240787d.png)

Am I doing anything wrong here? This is the behavior that I expect because this is how it works in Xamarin forms.

Many thanks,
Ben

**Comment by TimLariviere** [comment]
@gobeiil This has been fixed in the latest release (v.0.34.0)
Now Header/Footer supports ViewElement and don't just call ToString().

**Comment by gobeiil** [comment]
Awesome, I'll make sure I check the release notes next time, I only scanned the issues. Thanks!
