### ISSUE TITLE
Memory warning with AllControls on Android

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/Fabulous#384]
I played around with AllControls on Android, and received memory warnings. Was using my Motorola G5 Plus. While I don't think there was much else happening on the device at the time, one can never be sure. In any case, I'd just like to ask whether a Fabulous-based architecture (if well designed) is more memory heavy than other architectures. Feel free to close this with a simple "no" if that's the correct answer.

**Comment by SergejDK** [comment]
I get the same warning on the G6.
The AllControls-Example is there to show how one can do specific things but not made for performance in mind or anything else.

As far as I know that it needs more memory but not very noticable. 

@TimLariviere 
correct me if I am wrong

**Comment by cmeeren** [comment]
> not made for performance in mind

Sure, I get that - I just figured that unless there's an obvious memory leak (bug), an app as simple as that shouldn't trigger memory leaks. In that case, there might be something memory-heavy about Fabulous itself (at least by "default" without conscious memory optimizations), hence my question.

**Comment by TimLariviere** [comment]
@cmeeren Fabulous is memory-heavy because it builds upon XF (which itself is a big beast :) ) and needs to manage its own state (maybe not the most optimized).
Fabulous apps will be more heavy than other similarly optimized apps because of the double framework.

That said, it should raise memory warning in simple apps.
We need to optimize it. Maybe related to #383

**Comment by TimLariviere** [comment]
v2 does a way better job regarding performance and memory consumption. It has been created to allocate as least memory as possible
