### ISSUE TITLE
View.Stateful throws InvaildCastException

### ISSUE THREAD

**Issue by kleidemos** [fsprojects/Fabulous#398]
I did not understand how to use `View.Stateful` (or `View.WithInternalModel`). It throws exception in any case.

```fsharp
View.Stateful(
    fun () -> "State"
    , fun state -> View.Label(state)
)
```

```
Необработанное исключение: System.InvalidCastException: Не удалось привести тип объекта "System.Tuple`3[Microsoft.FSharp.Core.FSharpValueOption`1[Fabulous.DynamicViews.ViewElement],Fabulous.DynamicViews.ViewElement,System.Object]" к типу "Xamarin.Forms.Label".
   в Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   в <StartupCode$Fabulous-Core>.$ViewElement.Create@47-1.Invoke(FSharpValueOption`1 prev, ViewElement curr, Object target)
   в Fabulous.DynamicViews.SimplerHelpers.update@120.Invoke(FSharpValueOption`1 prevOpt, ViewElement source, Object target)
   в Fabulous.DynamicViews.ViewElement.Create()
   в <StartupCode$Fabulous-Core>.$Xamarin.Forms.Core.UpdateStackLayout@8338.Invoke(ViewElement x)
   в Fabulous.DynamicViews.Converters.updateCollectionGeneric$cont@277[T,TargetT](FSharpValueOption`1 prevCollOpt, IList`1 targetColl, FSharpFunc`2 create, FSharpFunc`2 attach, FSharpFunc`2 canReuse, FSharpFunc`2 update, T[] coll, Unit unitVar)
   в Fabulous.DynamicViews.Converters.updateCollectionGeneric[T,TargetT](FSharpValueOption`1 prevCollOpt, FSharpValueOption`1 collOpt, IList`1 targetColl, FSharpFunc`2 create, FSharpFunc`2 attach, FSharpFunc`2 canReuse, FSharpFunc`2 update)
   в Fabulous.DynamicViews.ViewBuilders.UpdateStackLayout(FSharpValueOption`1 prevOpt, ViewElement curr, StackLayout target)
   в <StartupCode$Fabulous-Core>.$Xamarin.Forms.Core.get_UpdateFuncStackLayout@8307.Invoke(FSharpValueOption`1 prevOpt, ViewElement curr, StackLayout target)
   в Fabulous.DynamicViews.ViewElement.Create()
   в Fabulous.DynamicViews.ViewBuilders.UpdateContentPage(FSharpValueOption`1 prevOpt, ViewElement curr, ContentPage target)
   в <StartupCode$Fabulous-Core>.$Xamarin.Forms.Core.get_UpdateFuncContentPage@10246.Invoke(FSharpValueOption`1 prevOpt, ViewElement curr, ContentPage target)
   в Fabulous.DynamicViews.ViewElement.Create()
   в Fabulous.Core.ProgramRunner`2..ctor(Application app, Program`3 program)
   в Fabulous.Core.ProgramModule.runWithDynamicView[model,msg](Application app, Program`3 program)
   в Fabulous.InvalidCast.MCVE.App..ctor() в C:\Users\MainKleiPC\Documents\Visual Studio 2017\Projects\Fabulous.InvalidCast.MCVE\Fabulous.InvalidCast.MCVE\Fabulous.InvalidCast.MCVE\Fabulous.InvalidCast.MCVE.fs:строка 69
   в Fabulous.InvalidCast.MCVE.WPF.Main.main(String[] _args) в C:\Users\MainKleiPC\Documents\Visual Studio 2017\Projects\Fabulous.InvalidCast.MCVE\Fabulous.InvalidCast.MCVE\Fabulous.InvalidCast.MCVE.WPF\App.fs:строка 19
```

**Comment by dsyme** [comment]
I don't think people are actively using this combinator.  There is a sample from when I authored it here: https://github.com/fsprojects/Fabulous/blob/6214fefa1073e5007652eaaada7d1cc5b5896693/extensions/SkiaSharp/SkiaSharp.fs#L74

However it is not under automated test, and so should definitely be considered experimental

**Comment by kleidemos** [comment]
This sample fails with the same error.

**Comment by kleidemos** [comment]
`realSource.Update(target)` instead of https://github.com/fsprojects/Fabulous/blob/89d2d9f002338fefd4d723b8d6cbe880d01cabf8/src/Fabulous.Core/ViewHelpers.fs#L123

But SkiaSharp still does not work.

**Comment by davidtme** [comment]
I have tried `realSource.Update target` locally and this works with SkiaSharp 

![image](https://user-images.githubusercontent.com/1804141/59340676-58beec80-8cfe-11e9-9714-a9dcf9c8971f.png)

**Comment by bra1nDump** [comment]
`View.WithInternalModel` is a related function, and also crashes. I believe its one of the most important view helpers since it does the following things:
* Increases performance in a simpler way than `dependsOn`
* Should yield better performance boost than `dependsOn`
* Makes the overall model & update logic simpler

```
    let view (_: unit) _ =
        View.ContentPage(
            content = 
                View.WithInternalModel(
                    init = fun () -> ()
                    , update = fun _ _ -> ()
                    , view = fun _ _ -> View.BoxView()
                )
        )
```

**Comment by bra1nDump** [comment]
@TimLariviere working on a bug fix for `View.WithInternalModel` & `View.Stateful`. Right now only if a single `ViewElement` is present in the tree returned by `view` function `View.WithInternalModel` works correctly.

Examples `view` body that works:
```
View.Button(
  text= sprintf "Increment internal counter (%d)" internalCounter, 
  command = localDispatch)
```
```
View.ContentView(
  View.Button(
    text= sprintf "Increment internal model (%d)" counter, 
    command = localDispatch)
)    
```

Example of that doesn't (children never get rendered):
```
View.StackLayout([ View.BoxView(Color.Black) ])
```

Prior to that I would like to identify/understand the need for `View.Stateful`. In the current implementation (after applying the fix suggested by @kleidemos ) it looks pretty useless. The state can be written to, but it will not affect the UI, unless dispatch of some message is not called.

**Comment by bra1nDump** [comment]
@TimLariviere did you remove proj/xamarinforms label because `Stateful` and `WithInternalModel` should both be under Fabulous project? I agree because these views are just proxies and don't make use of any XamarinForms API.

**Comment by TimLariviere** [comment]
@bra1nDump I only changed the labels to follow the new [Maintainer Guide](https://github.com/fsprojects/Fabulous/blob/master/.github/MAINTAINER_GUIDE.md) and `proj/xamarinforms` no longer exists.

But I agree with you that `Stateful`, `WithInternalView` and `External` look generic enough to be in Fabulous directly.

**Comment by bra1nDump** [comment]
There seems to be a need to a key parameter to both Stateful and WithInternalModel. Stateful implementation uses a table to store the state with the key being the real view reference. This is not going to work if Stateful and WithInternalModel views will be used on any type of collection views. I tried to find my way around using keys, but want able to do so. 

Right now the implementation for WithInternalModel looks something like this:
There is a table which stores 
1. prevViewElement
2. lastModel
3. last view reference passed in the update (XF.View) to make it work with reusable collection/list views
4. Last 'local' view function passed in the update. In the local dispatch I don't have reference to the 'proxy/combinator' view element that has that attribute

On a separate note I have been thinking that the code I wrote to get WithInternalModel to work is afully similar to the (mkSimple) Program code. Which led me to thinking about somehow reusing Program code?

I will keep sending updates on my work on this.

**Comment by bra1nDump** [comment]
Here is a link to place in [Fabulous.XamarinForms.Core/ViewHelpers.fs](https://github.com/bra1nDump/Fabulous/blob/e1a58acbebc12b12ad330a9f66519f96d6ee4efc/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/ViewHelpers.fs#L148) to the place in the file I  where my changes start. I am facing many difficulties both with implementation correctness and design.

The idea:
Have embedded simple sub-programs within the main program as part of the ViewElement hierarchy. Proposed name and parameters: `View.SimpleProgram(key, init, update, view)

Benefits:
* Simpler main model, update
* Faster dispatch, update, view cycles
Downsides: 
* Introducing mutability thus diverging from Elm architecture
* Not intuitive how existing sub-program can be updated when main program model changes. Ex: if init is updated, should the model be recreated? I think yes, but framework users might expect otherwise

Fundamental challenges

1. Local dispatch needs to have references to a lot of things (similar to how [processMsg](https://github.com/fsprojects/Fabulous/blob/fc080144a7d3b14ecc7326a897f40bf2128619fe/src/Fabulous/Program.fs#L61) references last model, update and view functions. Lets call those program.
    * In case with the main program dispatch all the references are kept in the singleton program runner
    * In our case there might be many programs. We need to somehow store at the very minimum the model for each of those programs. The approach introduced by storing model by target view reference in a weak table does not work mainly because of the point (2).

2. So looks like we need some sort of storage mechanism.
    * What do we use to address the sub-programs? Current solution involves using an int key supplied by `View.SimpleProgram` consumer upon creation.
    * How to prevent memory leaks? (currently the only correctness problem as far as I know)
    * Lets say we 'migrate' the simple program to a different part of the view, how do we keep the state? Should we keep the state? (This is a general issue with fabulous) 

Questions @TimLariviere :
I am trying to completely rework the initial idea of `View.WithInternalModel` as well as diverging the work from `View.Stateful` completely. Does it make sense to create a separate issue for this?

Looks like there is a very much related discussion going on in https://github.com/fsprojects/Fabulous/issues/678#issuecomment-592437365 so maybe no need to create a new issue?

Is this a viable approach to solving the problem with uncoupling different update cycles? I think the fact that separately multiple people are attempting to solve the same problem confirms that it exists but I would assume only one approach will be accepted as part of the main framework

**Comment by TimLariviere** [comment]
Closing this issue as this is no longer relevant to v2
