### ISSUE TITLE
Using ViewRef in View Extension

### ISSUE THREAD

**Issue by christoph-feb22** [fsprojects/Fabulous#415]
While creating a view extension for [Xamarin SignaturePad](https://github.com/xamarin/SignaturePad) I need the ViewRef for the ViewElement.
The documentation is clear in how to use ViewRef in default ViewElements but not how to implement ViewRef in extensions. They are also not implemented in the provided extensions.

If someone can help me how to implement the ViewRef, I can also extend the documentation with an example.

**Comment by TimLariviere** [comment]
`ViewRef<T>` needs to be initialized when creating the control you want to instantiate.
You need to call its `Set(target: T)` method.

This can be done inside the `create` function of a typical extension like this
```fsharp
type Fabulous.DynamicViews.View with
    static member YourControl(?ref) =

        // Count the number of additional attributes
        let attribCount = 0
        let attribCount = match ref with Some _ -> attribCount + 1 | None -> attribCount

        // Populate the attributes of the base element
        let attribs = 
            ViewBuilders.BuildView(attribCount, ?ref=ref)

        // The create method
        let create () =
            let instance = new SkiaSharp.Views.Forms.SKCanvasView()
            match ref with Some viewRef -> viewRef.Set(instance) | None -> ()
            instance

        // The update method
        let update (prevOpt: ViewElement voption) (source: ViewElement) (target: SKCanvasView) = 
            ViewBuilders.UpdateView (prevOpt, source, target)

        // The element
        ViewElement.Create(create, update, attribs)
```


You can find the implementation inside `ViewElement` here (uses `box` here because it's using `ViewRef` instead of `ViewRef<T>`):
https://github.com/fsprojects/Fabulous/blob/3d41b5b0a52f1665418f4ed378685799573557d1/src/Fabulous.Core/ViewElement.fs#L91-L102

**Comment by christoph-feb22** [comment]
Thank you very much for your fast help!
