### ISSUE TITLE
Update Android Support Libraries to v28 (matching Android 9.0)

### ISSUE THREAD

**Issue by TimLariviere** [fsprojects/Fabulous#442]
Like said by @PureWeen, we should update the templates to use the v28 packages of the Android Support Libraries.

Also I'm reconsidering the rule of the least major version for the templates #419
It's a good rule for our packages, since it would otherwise prevent users from using an earlier version of an external package we use if they really need it (like Newtonsoft.Json)
But is it really applicable to the templates?

Users are not blocked by it, but need to update the packages (like Xamarin.Essentials) each time they create a new template.

@SergejDK What do you think?

**Comment by mallibone** [comment]
Just to chime in - updating the libs to v28 and Android 9.0 would also allow the usage of Material Visuals aka beautiful Material designed apps.

As of the versions of NuGet packages (just my opinion 😇): Since there is no long term supported version of Xamarin Forms. I believe keeping it aligned with the C# template in VS could be a good strategy for now.

In general, I would concur with using the latest and greatest in the templates, i.e. not letting the user having to update to all the latest libs but keeping the dependencies from Fabulous as low as possible.

If it is not to time pressing or you are not already all over it, I could tackle the update. There are some different packages required for 9.0 as are currently referenced and the target files do not seem to update when updating the packages via VS2019 NuGet package manager - any idea why that may be?

**Comment by TimLariviere** [comment]
>the target files do not seem to update when updating the packages via VS2019 NuGet package manager - any idea why that may be?

@mallibone What files do you mean?

For the samples, the Android packages are downloaded by Paket but the path to the dlls are set by hand. 
For the templates, the packages are managed by NuGet (`packages.config`) but the version is replaced by a token declared in https://github.com/fsprojects/Fabulous/blob/master/templates/content/blank/.template.config/template.json

Maybe Visual Studio doesn't support updating `packages.config` when using tokens instead of versions?

>If it is not to time pressing or you are not already all over it, I could tackle the update

Sure. You're more than welcome to do it. Thanks! :)

**Comment by SergejDK** [comment]
The update to v28 is a great idea - I think there are some people who want to use Visuals.

> Users are not blocked by it, but need to update the packages (like Xamarin.Essentials) each time they create a new template.

If you create a new project you will normally have the latest packages in it or you want them in it because you have no dependencies in a new project to older parts. I do not know one person who do not update when they start a new project.
We should say 'updates only to stable versions' - just to be clear.

> In general, I would concur with using the latest and greatest in the templates, i.e. not letting the user having to update to all the latest libs but keeping the dependencies from Fabulous as low as possible.

This seems to be a good approach to me!

**Comment by TimLariviere** [comment]
@mallibone Just to let you know, I've updated the samples to Android Pie.
The templates still require an upgrade though.

**Comment by mallibone** [comment]
@TimLariviere cool I'll have to take a peek 😃 - I started with the update of the template and hope to be done soon 🤞

Since I am updating the templates should I also update the Essentials and XF packages to the latest updates? If I am not mistaken I would leave JSON.Net on the current version?

**Comment by TimLariviere** [comment]
>Since I am updating the templates should I also update the Essentials and XF packages to the latest updates? If I am not mistaken I would leave JSON.Net on the current version?

Yes, I think you can update them to the latest versions, even JSON.NET.

**Comment by TimLariviere** [comment]
Closed by #446 and #453
