### ISSUE TITLE
Picker: Selected item index is not maintained when the list is changed

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#465]
Minimal repro:
```fs
Program.mkProgram
    (fun () -> false, Cmd.ofMsg ())
    (fun () model -> not model, async { do! Async.Sleep 1000 } |> Cmd.ofAsyncMsg)
    (fun model _ -> View.ContentPage(View.Picker((if model then [1; 2] else [1; 2; 3]), selectedIndex = 0)))
```
The above code changes the list every second. The selected index is kept constant. However, the selected item unselected.

![image](https://user-images.githubusercontent.com/19922066/59913010-e6f74900-9449-11e9-912c-30daa6ef05ed.png)

Compare:
```fs
Program.mkSimple id (fun () -> id) (fun _ _ -> View.ContentPage(View.Picker([1; 2], selectedIndex = 0)))
```

When the list is unchanged, the selected index is set successfully.

![image](https://user-images.githubusercontent.com/19922066/59913272-713fad00-944a-11e9-91e7-5c4267d28268.png)

**Comment by SergejDK** [comment]
@Happypig375 does this  only occur on UWP or other platforms, too?
E.g. on Mac it works. Always 1 is selected.

**Comment by Happypig375** [comment]
Reproducible on Android (Android 8.1).

Changing list|Constant list
-|-
![image](https://user-images.githubusercontent.com/19922066/59961021-f509a000-9503-11e9-93df-9a0783556130.png)|![image](https://user-images.githubusercontent.com/19922066/59961022-faff8100-9503-11e9-8c66-381aae907953.png)

**Comment by SergejDK** [comment]
The default behavior from XF and for Android is that changing the ItemsSource sets the selectedIndex to -1. Because in Fabulous we only set the options like selectedIndex once it does not update when changing the itemssource - internally the index will be -1.

Little workaround would be set the selectedindex to 0 and then to 1 and back.

@TimLariviere 
maybe you have an idea for this?

**Comment by Happypig375** [comment]
Can we also set the selectedIndex when the itemsSource is changed? That would be a special case in code.

**Comment by SergejDK** [comment]
@Happypig375  
As far as I know it is currently not possible. 

Was thinking about some solutions:

Normally the behavior of Android/UWP maybe more is that the selectedIndex is set to -1 when the itemssource is changed.
```fsharp
match prevSelectedIndexOpt, currSelectedIndexOpt with
        | ValueSome prevValue, ValueSome currValue when prevValue = currValue -> () // this will be called even though the selectedindex is -1 but for fabulous still 0
        | _, ValueSome currValue -> target.SelectedIndex <-  currValue
        | ValueSome _, ValueNone -> target.SelectedIndex <- null
        | ValueNone, ValueNone -> ()
```

The first idea is that on every newValue we set the index again. This way it will be maintained. 
Changing the above code to:
```fsharp
match prevSelectedIndexOpt, currSelectedIndexOpt with
        | _, ValueSome currValue -> target.SelectedIndex <-  currValue
        | ValueSome _, ValueNone -> target.SelectedIndex <- null
        | ValueNone, ValueNone -> ()
```

Another idea would be to change the input to sth. like: 
```fsharp
selectedIndex=(int, bool) // int for the indexvalue; bool "dynamic"
```
The second approach could be better for performance because we would not always set the currentValue but it will be different to use. Therefore a custom updatecode would be needed. With the bool it would be possible to check for "defaultbehavior" or not.

@TimLariviere 
do you think one of those approaches seems good?

**Comment by TimLariviere** [comment]
A property that depends on another one is not something Fabulous really likes.
The truth of source needs to be the ViewElement, not some side effect from the underlying framework.

The way I can imagine to fix it is a custom update code for `ItemsSource` instead of `SelectedIndex`.
If the ItemsSource needs to change, we will need to automatically reapply the `SelectedIndex` if possible as well.

**Comment by SergejDK** [comment]
Was testing it:

```fsharp
let internal updatePickerItemsSource prevValue currValue curIndex  (target: Xamarin.Forms.Picker) = 
        let index = match curIndex with
            | ValueSome v -> v
            | ValueNone -> -1
        match prevValue, currValue with
            | ValueNone, ValueNone -> ()
            | ValueSome prevVal, ValueSome newVal when prevVal = newVal -> ()
            | _, ValueNone -> target.ItemsSource <- null; target.SelectedIndex <- -1
            | _, ValueSome newVal -> 
                target.ItemsSource <- newVal
                target.SelectedIndex <- index
```

This will work but I don't know if the Generator currently supports a UpdateCode with an extra parameter. Other way would be to write this function in the json file but I don't like to put it there.

**Comment by TimLariviere** [comment]
You're right. It's not possible for the moment, the Generator doesn't support it.
Before we're able to move forward on this issue, we will need to decide how we proceed with the Generator. (might heavily change if we do the framework agnostic view diffing)
