### ISSUE TITLE
Feature request: Support for Context Actions in ListView/TableView

### ISSUE THREAD

**Issue by katatunix** [fsprojects/Fabulous#520]
I would like to have `Context Actions` for each item/row in a `ListView` or `TableView`. From the [document](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/interactivity#Context_Actions) of Xamarin.Forms `ListView`, it supports `Context Actions`. So it would be great if we can have it in Fabulous too.

**Comment by TimLariviere** [comment]
Dev notes: The way I can see it implemented is by creating a fake attached property (e.g. "ViewCellContextActions") in the ViewAPI for all Elements (like Created/Ref)
Then in ViewElementCell, we will be able to read it and correctly set the ContextActions property of the ViewCell

**Comment by TimLariviere** [comment]
`ListView` has been changed to accept cell-derived types instead of directly labels and such to allow accessing the ContextActions.
Here's a documentation about it: https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/migration-guide-to-0.50.html#listview-and-listviewgrouped-now-require-items-and-group-headers-to-be-cells-adds-support-for-textcell--imagecell--switchcell--entrycell--viewcell

It will be released with v0.50 which will arrive in the coming days
