### ISSUE TITLE
Add option to include extensions when making template

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#526]
E.g. `dotnet new fabulous-xf-app --SkiaSharp --Oxyplot`
This reduces the time to find the packages then installing.
Also, this avoids bugs like #439 (which is still a problem for me).

**Comment by TimLariviere** [comment]
Sorry, but I don't think this would be a good idea.

We include options for the platform because it's boilerplate code and it's hard to write for the user.

But including options for some packages doesn't really make sense.
Adding packages is highly dependent on what the user is trying to achieve.

And also why theses packages and not all of them?
In the future, there will be more than the 5 extensions we have today.

This will increase amount of work we do on the templates exponentially.
Will we need to test all the possibles combinations to make sure eveything works: [Debug|Release] * [iOS|Android|WPF|...] * [SkiaSharp|Oxyplot|...]^All_Extensions

I think it's not worth it for the little usage.
People are used to add the packages themselves and not rely on a command line when creating the solution.
Especially since they might not know they will need those packages.

**Comment by Happypig375** [comment]
ok
