### ISSUE TITLE
Fabulous, Fabulous.Cli and Fabulous.LiveUpdate should be at the top level directory

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#543]
Alternatively, Fabulous.StaticView and Fabulous.XamarinForms should be in the src folder.

**Comment by Happypig375** [comment]
Or, the src folder should be renamed to something like Fabulous.Core

**Comment by TimLariviere** [comment]
Fabulous, Fabulous.XamarinForms and Fabulous.StaticView are 3 separate products now.
In the future, Fabulous.XamarinForms and Fabulous.StaticView might even go in their own GitHub repositories.
That's why I kept them in separate folders.

This repository is mainly structured for Fabulous itself and follows the classic `src`/`tools`/`tests` structure.
F.XF and F.StaticView reproduce this structure inside their own folder to be easily movable.

Is there an issue with this?

**Comment by TimLariviere** [comment]
I guess I could have put most of the files and folders of the root directory inside a folder called Fabulous.
It would have left only 3 folders at the root: Fabulous, Fabulous.XamarinForms and Fabulous.StaticView, which would have reflected those 3 products in 1 repo.

But given we're in the Fabulous repository, I preferred to keep Fabulous at the root directly.

**Comment by Happypig375** [comment]
Makes sense with this mental structure. Thanks.
