### ISSUE TITLE
Serialization Performance

### ISSUE THREAD

**Issue by aspnetde** [fsprojects/Fabulous#561]
I noticed that the default behavior in all demo apps so far is to serialize the model when the app "is going to sleep". As reality is more complex it could happen that one needs to save more often, for example to prevent losses of critical data in case of possible crashes (or at least to reduce the probability of such a scenario).

Is anyone doing this already who has also measured the execution time of the serialization process?

Context: I've run into serious performance problems with Newtonsoft JSON and large F# data structures in a Xamarin application. It is not using Fabulous (I've started the project way before Fabulous was born), but the principles are quite similar. I would be happy to hear about experiences in general and any tip or trick that helps to boost performance here in particular.

Cheers

Thomas

**Comment by SergejDK** [comment]
normally newtonsoft json is great.

Did you try to use [BSON](https://www.newtonsoft.com/json/help/html/SerializeToBson.htm) with Newtonsoft Json?

Compared to JSON, BSON is designed to be efficient both in storage space and scan-speed.

**Comment by TimLariviere** [comment]
While serializing the whole state in JSON seems like a nice feature, in reality, it's only really viable  for tombstoning/resuming only of small to medium apps.

When the app grows in size and complexity, keeping the whole state might not make the most sense in my opinion.

I would only save the crucial data (with Xamarin Essentials Settings, SQLite, etc.)
The rest is usually highly dependent on what the user is currently doing (the state of an Entry) or can easily be inferred from another data.

For critical data, I think it would be best to save them immediatly after being set. Like in the update method by using a function with side effect.

```fsharp
let setCriticalData data =
    saveCriticalDataInSQLite data
    { model with CriticalData = data }

match msg with
| SetCriticalData data -> setCriticalData data
```

Even when tombstoning, developers can only keep a subset of the state (like keeping only the id of a data coming from an API or database instead of all its properties), faster to serialize.

**Comment by aspnetde** [comment]
Thanks for your feedback, very much appreciated.

Regarding performance: We didn't check BSON for JSON.NET yet, as it is not even mentioned on the performance tricks page of its docs. But we found a couple of other libraries (e.g. [FsPickler](http://mbraceproject.github.io/FsPickler/tutorial.html#An-Introduction-to-FsPickler)) which we need to evaluate. However, most of them seem to have issues with F# types, especially with union types.

But eventually I agree with @TimLariviere. I like the idea that the app is kind of resilient of missing data, so it tries to fetch it from a local cache first, and then from a server second. However, this degrades the model/state somehow to a second-class citizen. And it obviously adds additional complexity to keep all the moving parts in sync.
