### ISSUE TITLE
ListView hasUnevenRows does not work perfectly

### ISSUE THREAD

**Issue by nghia-bui** [fsprojects/Fabulous#565]
Not sure whether this is a problem of Xamarin.Forms or Fabulous.

I have a ListView with different heights of its items. So I set `hasUnevenRows` to `true` and don't set the `rowHeight` property.

Problem is that the current (visible) items don't resize automatically. To make it works I have to either scroll down and up to make those items disappear and appear again, or rotate the phone.

With Xamarin.Forms I can use `Cell.ForceUpdateSize` but I don't know how to use it in Fabulous.

Is there any fix or workaround for this?

**Comment by TimLariviere** [comment]
Not the best solution but there's a way to access `Cell.ForceUpdateSize`.

The problem here is that Fabulous.XamarinForms implicitly creates for you a ViewCell for each item in your ListView (I think it might be a good thing to change that later).

The workaround is to use `ViewRef` to gain access to real XF control of your item (e.g. a Label) and then access its `Parent` property. This will be the cell itself.

```fsharp
let labelRef = ViewRef<Label>()

let update msg model =
    match msg with
    | ListLoaded  ->
        match labelRef.TryValue with
        | None -> ()
        | Some label -> (label.Parent :?> ViewCell).ForceUpdateSize()

        model

let view model dispatch =
    View.ContentPage(
        View.ListView([
            View.Label(ref = labelRef)
        ], hasUnevenRows = true)
    )
```

I must say I've already had issues with uneven rows in XF (not using Fabulous at that time).
I never found a satisfying solution to that problem and decided to go with a ScrollView/StackLayout instead...

**Comment by nghia-bui** [comment]
Thanks for the instruction on how to use `ForceUpdateSize`.

Regarding ScrollView/StackLayout, oh yes, while waiting for your answer I already switched to that approach. However this does not support _Pull To Refresh_ and _Item Appearing_.

Hopefully Fabulous will support [RefreshView](https://github.com/xamarin/Xamarin.Forms/issues/5882) in the next release.

**Comment by SergejDK** [comment]
@nghia-bui 
with Fabulous 0.50 RefreshView should work.
You can take a look at the AllControls-sample where @TimLariviere used it.
