### ISSUE TITLE
Xamarin.Forms.Visual.Material Support

### ISSUE THREAD

**Issue by kthompson** [fsprojects/Fabulous#569]
I would like to use Xamarin.Forms.Visual.Material with Fabulous using the same MVU style.

What would be needed to add support for this?

**Comment by TimLariviere** [comment]
Hi @kthompson 
Fabulous.XamarinForms already supports it.

To use it, follow the instructions here : https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual#initialize-material-renderers

And add the `visual` attribute to any view you like (adding it to the page will apply it to all controls)
```fsharp
View.ContentPage(
    visual = Xamarin.Forms.Visual.Material,
    content = (...)
)
```

**Comment by mallibone** [comment]
@TimLariviere is correct - you can use it, and I have done so myself. The biggest hurdle I encountered was adding the NuGet package via the visual Package Manager. My best guess is that it is an issue due to the "old" `package.config` style used in the platform projects. But I got around it by using the package manager console.

I wrote an sample a while back you can check it out [here](https://github.com/mallibone/FabulousIntro).

**Comment by kthompson** [comment]
Thanks! I will check it out.
