### ISSUE TITLE
Restricting Entry input

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#571]
```fs
Program.mkSimple (fun () -> "0")
    (fun msg _ -> match msg with "0" | "1" -> msg | _ -> "0")
    (fun m d -> View.ContentPage(View.Entry(m, textChanged = fun e -> d e.NewTextValue)))
```
This is a program with an entry that should limit its own value to 0 or 1. However, due to view diffing, repeatedly setting the model to `"0"` has no effect. Is there a way to accomplish this?

**Comment by TimLariviere** [comment]
That's an interesting use case.

While it seems pretty straightforward, I'm wondering if it's not a limitation of the view diffing model based on previous-next states...

Like you said, the UI did changed but Fabulous is not aware of it. It will then do nothing, since nothing changed from its point of view.
Unfortunately checking the UI to see if we need to reapply that would kill all the possible perf tricks we can currently do (e.g. `dependsOn`)

One way you could accomplish what you want is to accept the new text so that the previous ViewElement is updated, and then immediately correct the text.

```fsharp
let validateTextCmd value =
    match value with
    | "0" | "1" -> Cmd.none
    | _ -> Cmd.ofMsg (SetText  "0")

let update msg model =
    match msg with
    | TextChanged value -> { model with Text = value }, (validateTextCmd value)
    | SetText value -> { model with Text = value }, Cmd.none

let view model dispatch =
     (...)
         View.Entry(text = model.Text, textChanged = (fun e -> dispatch (TextChanged e.NewTextValue)))

```

**Comment by Happypig375** [comment]
This will still be a problem if e.g. the model is using a `TimeSpan`, and the entries are editing the hours and minutes of the time. Will this require extra fields in the model for user-inputted text? If so, then this seems to be boilerplate code.

**Comment by TimLariviere** [comment]
What I would do in your case is to write a small custom control that will enforce the accepted inputs and only raise an event when the whole input is valid, much like a masked entry.
Because it's more of a technical rule than a business one.

```fsharp
type MaskedEntry() as self =
    inherit Entry()

   do self.TextChanged.Add self.OnTextChanged

    let textValidated = Event<EventHandler<TextChangedEventArgs>, string>()
    [<CLIEvent>] member __.TextValidated = textValidated.Publish

    member this.OnTextChanged(sender: MaskedEntry, args: TextChangedEventArgs) =
        match args.NewTextValue with
        | "0" | "1" -> textValidated.Trigger(self, args.NewTextValue)
        | _ -> self.Text <- "0"
```
You would then need to write a small wrapper to use it in your views
See https://github.com/TimLariviere/FabulousContacts/blob/master/FabulousContacts/Controls/BorderedEntry.fs

This way you can easily write
```fsharp
let setHours = fun hours -> dispatch ...
let setMinutes = fun minutes -> dispatch ...
let setSeconds = fun seconds -> dispatch ...

View.MaskedEntry(text = model.Hours, textValidated = setHours)
View.MaskedEntry(text = model.Minutes, textValidated = setMinutes)
View.MaskedEntry(text = model.Seconds, textValidated = setSeconds)
```

The advantage is that it's completely reusable, it doesn't pollute your model (and even simplify it).
And with a little change, you could make it accept all sort of masks that it will be able to enforce generically.

Otherwise, if you don't want to write it yourself, there are several masked entry already existing in libraries like SyncFusion, or opensource GitHub repos.

**Comment by TimLariviere** [comment]
I guess the initial question has been solved.
