### ISSUE TITLE
FSharp.Core.FSharpCorePkgVersion in templates does not change ref path to netstandard2.0 when F# 4.7 is used

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#582]
https://github.com/fsprojects/Fabulous/blob/24ff0c945d4f8cf812e6bc81465c1aabcc509af0/Fabulous.XamarinForms/templates/content/blank/NewApp.iOS/NewApp.iOS.fsproj#L169
As a result, lines like these get generated:
```
<HintPath>..\packages\FSharp.Core.4.7.0\lib\netstandard1.6\FSharp.Core.dll</HintPath>
```
which does not exist because F# 4.7 has upgraded to target .NET Standard 2.0.

This results in the default FSharp.Core to be referenced, which is an ancient version.
It causes errors like this on Xamarin.iOS:
```
System.FileNotFoundException: Missing image: FSharp.Core.resources.dll
```

**Comment by TimLariviere** [comment]
Thanks for the report.

Are you setting the FSharp.Core version via the command line?
e.g. `dotnet new fabulous-xf -FSharpCorePkgVersion 4.7.0`

I'm wondering if it's really useful in this case.

This issue is mostly just a side effect of the way we parametrize the version numbers, and is not really intended to be settable by command line.

Typically, I would expect users to only use platform flags `--WPF` and update package versions through their IDE, like any other templates.

**Comment by TimLariviere** [comment]
Templates now target F# 4.7 by default, so it is no longer an issue.
