### ISSUE TITLE
Icon missing on TabbedPage when set via .Icon (iOS)

### ISSUE THREAD

**Issue by marcelstuder** [fsprojects/Fabulous#660]
# Issue

When setting an icon on a `ContentPage-ViewElement` using `.Icon(Path "myicon.png")` it won't be displayed (iPhone 11, iOS 13.3 - simulator and real device). The same icon will be displayed when setting it via `icon=Path "myicon.png", `

I have created a small sample that demonstrates the issue (using fabulous 0.51.0):
https://github.com/marcelstuder/MissingIcons

## Screenshot

![image](https://user-images.githubusercontent.com/10497964/73733414-315cda00-473c-11ea-936d-45cdb4d52e4c.png)

## Workaround

![image](https://user-images.githubusercontent.com/10497964/73733427-36ba2480-473c-11ea-8f66-7ce8d38806a8.png)

Isn't this supposed to work either way or am I missing something?

**Comment by SergejDK** [comment]
@TimLariviere 
Couldn't take a very detailed look on this but found out something.
Using the property `icon=Path ...` results in a Xamarin.Forms ImageSource
where using `.Icon(...)` results in a normal Imagesource. 
I think the convertpart is missing somewhere...

**Comment by SergejDK** [comment]
@marcelstuder 
please use `.IconImageSource` instead of `.Icon`.
`Icon` is obsolete since XF 4.0

@TimLariviere
should we maybe remove `.Icon`?

**Comment by marcelstuder** [comment]
@SergejDK I will switch to .IconImageSource - thank you for your valuable input!

**Comment by TimLariviere** [comment]
@SergejDK This issue is actually subtle. It's linked to the fact `ViewElement` is not typed (it's `ViewElement`, not `ViewElement<ContentPage>`).

Each property from each control will have a corresponding extension setter (e.g.`View.ContentPage(...).Title(...)`).
But the generator will add those extension setters directly to `ViewElement`, resulting in having access to all properties of all controls when writing `View.ContentPage(...).Something`.

We already removed `Icon` from `Page` since it has been deprecated and replaced it with `IconImageSource` (short name `icon` => `View.ContentPage(icon=Path ...)`).

But since `BaseShellItem` also has a valid `Icon` property, when writing `View.ContentPage(...).Something`, `.Icon(...)` will appear valid when it really isn't for ContentPage.

Hence why `.Icon(...)` doesn't work but `.IconImageSource(...)` does.

#341 is required to fix this issue.

**Comment by TimLariviere** [comment]
v2 introduces strongly-typed DSL, so IntelliSense will recommend only compatible modifiers.
