### ISSUE TITLE
Downgrade to FSharp.Core?

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/Fabulous#681]
I have an existing Fabulous project in VS For Mac 2019.  I upgraded Fabulous to 0.52 and now I am getting the following warning: Detected Package Downgrade

<img width="355" alt="Screen Shot 2020-03-01 at 7 30 40 AM" src="https://user-images.githubusercontent.com/1394644/75625728-f741f500-5b8e-11ea-97d5-fe47834c967b.png">

Is Fabulous just that far behind FSharp.Core?

**Comment by TimLariviere** [comment]
@jamessdixon Fabulous uses FSharp.Core 4.6.2 (or higher) (see Dependencies in https://www.nuget.org/packages/Fabulous/0.52.0).
But your project `sameroom.mobile.core` has a direct reference to FSharp.Core 4.5.2 or higher (might be implicit like found in https://github.com/mono/monodevelop/pull/5137).

This makes Visual Studio want to downgrade the version required by Fabulous, since FSharp.Core 4.5.2 is a direct dependency.

So I think if you update your `FSharp.Core` version to `4.6.2` minimum in the `sameroom.mobile.core` project, the warning will disappear.

As a general rule, you should include a direct reference to the highest version FSharp.Core in your output project.
https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#applications-should-target-higher-versions-of-fsharpcore

**Comment by jamessdixon** [comment]
Thanks Tim
