### ISSUE TITLE
Xamarin.Forms 4.5

### ISSUE THREAD

**Issue by Liminiens** [fsprojects/Fabulous#682]
https://devblogs.microsoft.com/xamarin/xamarin-forms-4-5/

It would be nice to have a MediaElement wrapper :)

**Comment by Happypig375** [comment]
Given that [it took 2 months for Fabulous to update to Xamarin Forms 4.4,](https://github.com/fsprojects/Fabulous/pull/644) you will most probably need to wait a similar amount of time to be able to use this.

**Comment by TimLariviere** [comment]
One can speed the availability of support for XF 4.5 by sending a PR ;)

Here's all the steps for such a PR:
- Update the used version of Xamarin.Forms for [NuGet](https://github.com/fsprojects/Fabulous/blob/master/Packages.targets) and [Paket](https://github.com/fsprojects/Fabulous/blob/master/paket.dependencies) (lowest major version only - eg. 4.5.0.356)
- Update the [JSON file](https://github.com/fsprojects/Fabulous/blob/master/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json) that generates the wrappers according to the [API changes of XF 4.5](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.5/4.5.0-api)
- Add samples for the new controls/properties in the [AllControls project](https://github.com/fsprojects/Fabulous/tree/master/Fabulous.XamarinForms/samples/AllControls)
- Write any appropriate [unit tests](https://github.com/fsprojects/Fabulous/tree/master/Fabulous.XamarinForms/tests/Fabulous.XamarinForms.Tests)
- Write any appropriate [documentation](https://github.com/fsprojects/Fabulous/tree/master/docs/Fabulous.XamarinForms)

Even if just the 2 first points are done and a PR is submitted, this will be an immense help for us. :)

**Comment by vshapenko** [comment]
@TimLariviere, are there any thoughts about simplifiying the process? Currently it looks routine and boring, so would be great to have a kind of guidance (from you, as a maintainer), how to simplify it. Maybe some code needs to be rewritten, some concepts need rethink. I am ready to put my resources on such tasks(cause this is important for the future of project i am developing currently), but i need a guidance.

**Comment by TimLariviere** [comment]
@vshapenko Unfortunately, there's only so much you can simplify or automate.

>Maybe some code needs to be rewritten, some concepts need rethink

I guess there's always different ways we could go, but as of right now, there's no significant changes I can think of that would simplify this process without rewriting Fabulous entirely.

>Currently it looks routine and boring

Yes, it kinda is. The main difficulty to support a new version of Xamarin.Forms is that one needs to go through the API changes to understand what new, changed or deprecated features there are in the release, as well as think of how those features could be used in a functional way.

Fabulous.CodeGen automates about 95% of the necessary code to make wrappers. But since Xamarin.Forms is written by people, it requires people to understand what's the real intention behind things and how it would be best translated in a functional programming language.

It requires a lot of time to go through the announcements, check out the C# samples, etc. to have a grasp of what's new and important in the release.

>I am ready to put my resources on such tasks(cause this is important for the future of project i am developing currently), but i need a guidance.

What I will provide (and should have provided earlier) is a documentation on how to analyze the [API changes of Xamarin.Forms](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.5/4.5.0-api) (because it might seems scary at first, but in fact there is only a few things we really need to look for) and how to configure the JSON file/add helper functions so the proper wrappers are generated.

For now, there's only a raw description of the JSON file format: https://github.com/fsprojects/Fabulous/blob/master/docs/Fabulous.CodeGen/codegen-bindings.md
