### ISSUE TITLE
iOS Larger Text (Dynamic Type) not effective immediately

### ISSUE THREAD

**Issue by katatunix** [fsprojects/Fabulous#703]
On my iPhone device, when I change the text size via Settings / Accessibility / Display & Text Size / Larger Text,

I noticed that the text size (in Labels with Named Font Size) of my app does not change immediately. I have to kill the app and open it again to see the new text size.

I know that it is possible to catch the event of text size change via `UIApplication.Notifications.ObserveContentSizeCategoryChanged` but don't know what to do when the event happens.

Is there any way to force the text size change be effective immediately?

I'm using the newest & stable version of Xamarin.iOS, Xamarin.Forms, and Fabulous.

**Comment by TimLariviere** [comment]
Seems like an issue with Xamarin.Forms itself.
It's supposed to work out of the box according to docs, but can't get it working in a C#/XAML app.
But on Android, it works.

**Comment by SergejDK** [comment]
@katatunix 

This is still an issue but maybe I know that the XF-Team is working on the accessibility features and explicitly for maui. maybe this will get better in the future.

A possible workaround but personally I didn't programmed it myself. The idea which I have is the following:
- Create a Resourcedictionary with different labelsizes and bind them to the labels/namedsizes
- React on the Event you mentioned -> `UIApplication.Notifications.ObserveContentSizeCategoryChanged`
- In the event you could get the correct sizes and set them so that the resourcedictionary is correctly updated and the labels

the dictionary is not the only solution but I hope the idea gets clear
