### ISSUE TITLE
selectionChanged signature broken after upgrade to XF 4.6

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#732]
For now it is (ViewElement list option*ViewElement list option) -> unit
insted of SelectionChangedEventArgs -> unit.

It affects CollectionView and others controls like listview

**Comment by TimLariviere** [comment]
Ah, yes. Changed the signature because it was exposing some internal components of Fabulous.
Now it returns directly the previously selected ViewElement as well as the newly ones.

See example here:
https://github.com/fsprojects/Fabulous/blob/e7f4d7cdb70712be515f52d14e83db6f805ce044/Fabulous.XamarinForms/samples/Shell/Fabimals/Fabimals/Components/AnimalListPage.fs#L39-L44

**Comment by vshapenko** [comment]
Yes, i found this place :) . Looks like this should be mentioned in update
guide

вт, 5 мая 2020 г. в 16:48, Timothé Larivière <notifications@github.com>:
