### ISSUE TITLE
Project works on debug but not on release

### ISSUE THREAD

**Issue by MicaelMor** [fsprojects/Fabulous#737]
Hi,

I am having an issue with a Fabulous android project, where during Debug everything works fine both on the android emulator and on an actual android device, however when I go from a debug build to a release build, the application starts giving a problem related to the npgsql.dll, which is required by me to access a database, it gives the following error message:

https://i.imgur.com/OGaUlg2.png

> Unable to resolve assemblies. One of Npgsql.dll must exist in the paths: 
> "C:\Users\Username\Documents\Visual Studio 2019\Projects\ReleaseErrorTest\ReleaseErrorTest
> /
> Details:
> resolutionPath directory doesn't exist:C:\Users\Micael\Documents\Visual Studio 
> 2019\Projects\ReleaseErrorTest\ReleaseErrorTest

This happens with the basic action of just simply creating a context from the SQLProvider (which uses Npgsql for postgresql databases), and once again only gives an error on the release build.
I have disabled all linking, so the build being created should be the full build with all dependencies.

For easier testing I have created a ready to use project:

https://github.com/MicaelMor/ReleaseErrorTest

The project has the bare minimum to reproduce the error, you press the button and the software tries to create a database context, if it fails it displays the exception message, if it succeeds it says there was no error.

I have also included with the project the string to an empty postgresql database that can be used, so there is no need to create a database to try and solve this error, the only thing that should be needed to run the project should be to create an Android 9.0 API 28 emulator.

This project was created using the template as per the documentation https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/

Should also add that I have also created elmish.wpf projects that used npgsql.dll and sqlprovider with the exact same structure (identical code for creating the context) and they worked both on debug and release builds, so it seems to be a problem that is happening specifically with fabulous projects, ~~I have also tried to create a xamarin C# project, with an F# backed project, and didn't get this error, although I wasn't using elmish and instead was initializing the database context in the c# project, so it wasn't a 1:1 test.~~
I have since the original post retested the C# project, and found I might not have been running it as release, since the error is very much present in that version, indicating 2 things to me:

First this is not a fabulous exclusive issue, but an Xamarin build related one.
Second as indicated by TimLariviere the issue almost certainly comes with the use of "__SOURCE_DIRECTORY__" where in the standard fsharp .net core builds this is likely replaced with the final location of the files indicated there, with .net standard xamarin builds this is likely not happening, and instead the "__SOURCE_DIRECTORY__" gets replaced with the original development machine directory, more than likely indicating why it is even trying to look into ReleaseErrorTest\ReleaseErrorTest instead of ReleaseErrorTest\npgsql, like it does during development.

Any suggestions on how to fix this would be welcome.

Thank you.

**Comment by TimLariviere** [comment]
Hi @MicaelMor,

I noticed 2 things that will make your app fail most likely:

- Using `__SOURCE_DIRECTORY__ `

`__SOURCE_DIRECTORY__ ` will always give you the path where you built the project (e.g. `C:\Users\Username\Documents\Visual Studio 2019\Projects\ReleaseErrorTest\ReleaseErrorTest`)

It is only useful when you're fiddling with scripts, not when you're building an app.
Here, it's trying to load dynamically a dll off of your computer's disk while running the app on your phone, which will fail at runtime, you can guess why.

- Doing dynamical things in Release mode

It's usually a bad idea to do dynamical things on iOS/Android because of the Linker.

In release mode, the compiler will call the linker. The linker's purpose is to remove everything you're not using to have the smallest app possible (e.g. 99% of the .NET Framework is useless in your application, even most of the code of Fabulous.XamarinForms is not needed in your example).

This is the difference between a 100MB app and a 1MB app in the store. Your users won't be happy if your app is too big.

But when doing reflection or loading a dll dynamically, the linker isn't aware of that and will most likely delete the dll/code associated to it.

I guess it's what happening here with npgsql.

It's working in Debug mode because when asking for `C:\Users\Micael\Documents\Visual Studio
2019\Projects\ReleaseErrorTest\ReleaseErrorTest\npgsql\npgsql.dll` it will fail to find this dll (your phone isn't your computer). But it happens that you reference a `npgsql.dll` in the Android project coming from a NuGet package. I think SqlDataProvider will use this one instead.

In Release mode, the linker will remove `npgsql.dll` since you're not using it directly.
And so, SqlDataProvider will fail since it can't find any `npgsql.dll`.

In my opinion, you need to find how to use SqlDataProvider with the npgsql NuGet package without loading the dll dynamically.

Maybe ask https://github.com/fsprojects/SQLProvider ?

**Comment by MicaelMor** [comment]
Hi,

Thanks yeah I already had to disable linker since the build was causing error because of it, in the end it would still work for me since this is going to be used for internal enterprise applications, so the app ending up being bigger is not a big issue the current application, but yeah thanks for the tip on it.

Linker issues aside, I still find the behavior to be a bit unexpected, because I have tested the code that is causing the issue with the "__SOURCE_DIRECTORY__" thing in elmish.wpf projects that were deployed to non development PCs, and they had no issues finding the .dll files.
As commented I also created a C# project that was calling the F# project and that project presented no issues on the release version, while I would have expected a similar behavior if it was a purely Xamarin mobile related difference, also while I didn't mention in the original post, I do reference SQLProvider and NPGSQL on the fsharp android project from nuget, to the best of my knowledge those are the files that end up going to the release/debug build, in fact if I didn't include them even the Debug version wouldn't run.

That being said will follow your advice and see if there is any way to remove the resPath, since it would indeed probably solve the problem.

Thank you, and if anyone has any other suggestions, or has run into a similar issue and solved it, please let me know.

**Comment by TimLariviere** [comment]
For this part:
>Linker issues aside, I still find the behavior to be a bit unexpected, because I have tested the code that is causing the issue with the "SOURCE_DIRECTORY" thing in elmish.wpf projects that were deployed to non development PCs, and they had no issues finding the .dll files.

I guess it's because of this
>It's working in Debug mode because when asking for C:\Users\Micael\Documents\Visual Studio 2019\Projects\ReleaseErrorTest\ReleaseErrorTest\npgsql\npgsql.dll it will fail to find this dll (your phone isn't your computer). But it happens that you reference a npgsql.dll in the Android project coming from a NuGet package. I think SqlDataProvider will use this one instead.

WPF has no equivalent to the linker of Xamarin. So in you published app, the `bin` folder should have the `npgsql.dll` because you have it as a reference in your project.
And when SqlDataProvider can't find the exact path with `SOURCE_DIRECTORY` it defaults using the behavior of Windows: first look next to the exe for a similarly named dll, then in the System32 folder.

**Comment by vshapenko** [comment]
@MicaelMor , add to your fsproj <None Include ="npgsql\yourdll.dlll" CopyToOutputDirectory="CopyAlways"/>. This would solve your problem

**Comment by MicaelMor** [comment]
> @MicaelMor , add to your fsproj
> following line(may contain misspelling:
> 
> ```
>  <None Include ="npgsql\yourdll.dlll" CopyToOutputDirectory="CopyAlways"/>
> ```
> 
> This would solve
> your problem

Thanks for the suggestion, had already tried it, and unfortunately it doesn't solve the issue, the problem is unlikely to be in the npgsql.dll being in the output directory, since I can find it there, also as mentioned I do include npgsql using nuget, so there is really no reason to think it wouldn't make its way there like all the other packages.

Right now the issue seems to be that when SQLProvider doesn't know where to find the npgsql.dll it looks for it in places it would find in a normal non-mobile project, but that just simply don't exist in a mobile one.

The problem is compounded by the fact there is apparently a slight issue with System.Threading.Tasks.Extensions on xamarin https://forums.xamarin.com/discussion/134422/could-not-load-assembly-system-threading-tasks-extensions and this package is used by SQLProvider.

The all npgsql thing is already a bit of a recurring problem with the SQLProvider project, so I am hoping to get an answer there since maybe someone will have already solved this issue.

**Comment by vshapenko** [comment]
@MicaelMor ,yes, my bad.

**Comment by TimLariviere** [comment]
Closing since it's not directly related to Fabulous.
