### ISSUE TITLE
Why do fix and fixf not have an extra parameter of DoNotUseMe?

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#741]
As mentioned in https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/views-perf.html, `dependsOn` has an extra parameter of type `DoNotUseMe`. However, `fix` and `fixf` do not have this parameter. Why is this so?

**Comment by TimLariviere** [comment]
`dependsOn` has an explicit `DoNotUseModelInsideDependsOn` to let you shadow the real model to catch if you're using a non-dependsOn value inside the function.
It's only really there to help you avoid invalid code, nothing prevents you from naming the DoNotUse parameter `_` and do something invalid.

```fs
dependsOn (model.A, model.B) (fun model (a, b) ->
    // Will not compile since model is DoNotUseModelInsideDependsOn,
    // but only because we named the function parameter the same than the model
    View.Label(text = model.C)
)

dependsOn (model.A, model.B) (fun _ (a, b) ->
    // Will compile, but when model.C changes, it won't reevaluate the function
    View.Label(text = model.C)
)
```

For `fix` and `fixf`, the use is a little different. It's there to cache a function that has no dependency (except `dispatch`).
There is no direct relation to `model`, so the need for an additional `DoNotUse` parameter has no real added value since no dependency at all should be used.

**Comment by Happypig375** [comment]
`fix` and `fixf` should not use model in the same way as `dependsOn`. What makes them different?

**Comment by Happypig375** [comment]
`fix` and `fixf` is really `dependsOn () (fun model () -> ...)`.

**Comment by TimLariviere** [comment]
`dependsOn` is meant for declaring the creation of a ViewElement that won't be reevaluated each time the view function is called.
`fix`/`fixf` are meant for caching more general functions, like callbacks.

Even if you can write an equivalent of `dependsOn` with `fixf (fun () -> View...)`, their usage are not the same.

Here's an example:
```fs
dependsOn model.A (fun model a ->
    View.Button(
        command = fixf (fun () -> dispatch Click)
    )
)
```

`fix`/`fixf` is only useful when you need the function to remain the same instance throughout multiple view calls.

Example:
```fs
let dispatchClick dispatch =
    let mutable count = 0
    fun () ->
        count <- count + 1
        dispatch (Click count)

// Will dispatch 1, 2, 3, etc.
View.Button(
    command = fix (dispatchClick dispatch)
)

// Will dispatch 1, 1, 1, etc. because the command is reset since 2 functions in F# can't be compared
View.Button(
    command = (dispatchClick dispatch)
)
```

**Comment by Happypig375** [comment]
Okay thanks
