### ISSUE TITLE
IndicatorColor property missing from IndicatorView

### ISSUE THREAD

**Issue by Ryan-Palmer** [fsprojects/Fabulous#769]
The IndicatorView should have two colour properties, indicatorColor and selectedIndicatorColor.

The selectedIndicatorColor property is there, but indicatorColor is missing.

You can see the property used here in the XF docs:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview#create-an-indicatorview

**Comment by TimLariviere** [comment]
@Ryan-Palmer Thanks for the report.
This is likely an oversight when we mapped the IndicatorView control.

This can be easily fixed by adding a mapping for `IndicatorColor` in this file:
https://github.com/fsprojects/Fabulous/blob/fb4f251ce5e7cd3f9755099dcd6f12991bcce794/Fabulous.XamarinForms/src/Fabulous.XamarinForms/Xamarin.Forms.Core.json#L2775-L2804

**Comment by Ryan-Palmer-CIT** [comment]
Awesome, thanks Tim! Really enjoyed your Xamarin vids with Don the other day. Just been giving Fabulous a go for the first time this week, I hope to get involved and start contributing soon :)
