### ISSUE TITLE
Button doesn't disable if the command is set

### ISSUE THREAD

**Issue by Blener** [fsprojects/Fabulous#815]
When a button has the command property set it doesn't get disabled.

```
let view (model: Model) (dispatch: Msg -> unit) =
        View.ContentPage(
          content = View.StackLayout(padding = Thickness 20.0, verticalOptions = LayoutOptions.Center,
            children = [
                View.Button(text = "Disabled with command", isEnabled = false, command = ignore)
                View.Button(text = "Disabled without command", isEnabled = false)
            ]))
```

The code above generates this:
![image](https://user-images.githubusercontent.com/7217205/99327236-3ec0fc00-2858-11eb-9437-aaf81cf1edec.png)

This was using Fabulous 0.57.0 on an Android emulator.

Thanks.

**Comment by TimLariviere** [comment]
@Blener Hi. Thanks for the report, but it's the default behavior of Xamarin.Forms.

A command comes with its own `CanExecute` property that overrides `IsEnabled`. If not explicitly set through `commandCanExecute`, it will default to `true` so the button will always be active regardless of `isEnabled`.

So when using commands in Fabulous, use `commandCanExecute` to switch between enable and disable instead of `IsEnabled`.

```fs
View.Button(text = "Disabled with command", command = ignore, commandCanExecute = false)
```

**Comment by Blener** [comment]
Hi @TimLariviere . My mistake then, sorry for that. Thank you for the help.
