### ISSUE TITLE
Can we add new frontend UI framework in version.2 ?

### ISSUE THREAD

**Issue by RickyYChan** [fsprojects/Fabulous#984]
I've noticed Version.2 for a while and it came out a few days ago. In Version.1 we have codegen, although it lacks documents. 
Is it possible to add any other UI Controls to Fabulous instead of using XF?

**Comment by Happypig375** [comment]
@edgarfgp has expressed interest in creating a Uno frontend after the MAUI one is finished.

Meanwhile, you can also give https://github.com/fsprojects/Avalonia.FuncUI a try.

**Comment by RickyYChan** [comment]
> @edgarfgp has expressed interest in creating a Uno frontend after the MAUI one is finished.
> 
> Meanwhile, you can also give https://github.com/fsprojects/Avalonia.FuncUI a try.

Thanks for your reply. I've tried FuncUI a long time ago. 
So it seems that there's no CodeGen in ver.2. And if we want a new UI framework, we should write our own code.

**Comment by TimLariviere** [comment]
>Is it possible to add any other UI Controls to Fabulous instead of using XF?

Yes, Fabulous can support more UI frameworks. Right now, I'm working on adding Fabulous.Maui.

CodeGen v1 was needed since it was the one generating all the core diffing logic for each control, this was an awful lot of code to write by hand otherwise.

In v2, it's not the case anymore. We use a central diffing logic, leaving very little work to do to support new frameworks.

You can see it like that: instead of mapping through JSON, controls are mapped via F# now.
It's not any more difficult, but you can be more fine-grained in how you want your users to use a certain control.

Example of Button:
https://github.com/fsprojects/Fabulous/blob/v2.0/src/Fabulous.XamarinForms/Views/Controls/Button.fs

**Comment by RickyYChan** [comment]
> > Is it possible to add any other UI Controls to Fabulous instead of using XF?
> 
> Yes, Fabulous can support more UI frameworks. Right now, I'm working on adding Fabulous.Maui.
> 
> CodeGen v1 was needed since it was the one generating all the core diffing logic for each control, this was an awful lot of code to write by hand otherwise.
> 
> In v2, it's not the case anymore. We use a central diffing logic, leaving very little work to support new frameworks.
> 
> You can see it like that: instead of mapping through JSON, controls are mapped via F# now. It's not any more difficult and you can be more fine-grained in how you want your users to use a certain control.
> 
> Example of Button: https://github.com/fsprojects/Fabulous/blob/v2.0/src/Fabulous.XamarinForms/Views/Controls/Button.fs

Thanks, ill check the link.
